var progress = [
    {
        title: "",
        url: "L01_010.html",
        transcript: ""
    },
    {
        title: "",
        url: "L01_010_2.html",
        transcript: ""
    },
    {
        title: "",
        url: "L01_010_3.html",
        transcript: {
            vid1: "<p>“Modern-day slavery,” “trafficking in persons,” and “human trafficking” are all umbrella terms for the act of recruiting, harboring, transporting, providing, or obtaining a person for compelled labor or commercial sex acts through the use of force, fraud, or coercion.  Other terms you might hear associated with human trafficking include involuntary servitude, slavery, debt bondage, and forced labor. Any minor under the age of 18 involved in commercial sex is always a victim of human trafficking, regardless of whether force, fraud, or coercion are present.</p>\
            <p>Human trafficking can include, but does not require, movement.  People are considered trafficking victims regardless of whether they were born into a state of servitude, were exploited in their home town, were transported to the exploitative situation, previously consented to work for a trafficker, or participated in a crime as a direct result of being trafficked.</p>",
            vid2: "<p>Human trafficking occurs both domestically and internationally, including on and around DoD military installations. Traffickers look for victims in vulnerable situations due to child abuse, sexual assault, adverse childhood events, economic hardship, political instability, natural disasters, as well as other causes. Sex trafficking victims are most frequently women and children and they can be U.S. citizens or foreign nationals. Traffickers also exploit people who are vulnerable because of their age, social, economic, or immigration status. In the U.S., traffickers frequently target runaway or homeless youths who have histories of physical or sexual abuse.</p>",
            vidgrp1vid1: "<p>One day I saw an ad in the newspaper that U.S. Army contractors [were] recruiting people to Afghanistan. In that advertisement they were recruiting for food servicing. I have already experience in food servicing area, so I thought of applying [for] it. I went to the office address which was mentioned in the newspaper. It is in North India. To reach there, I had to travel 36 hours by train from my hometown to the office address.</p>\
            <p>Some people  asked [for] $3000 whereas some asked [for] $3500. [At] that time I don't have that much money with me. So I waited almost one and a half months with the hope that some other sub-agent might ask [for] some less[er] amount. And finally I got a call from [a] sub-agent who asked [for a] less[er] amount. The amount is ₹80,000 which is comparatively less to what others asked. But still this 80,000 is [a] big amount for me. It's almost my eight-month salary back then in India. But I don't have any other choice, because other agents were asking huge money.</p>\
            <p>So I said okay to this agent, and I said I will arrange the money anyhow. But please get me this job. And they said, \"You give us the money, we will get you this job.\" He mentioned the salary as for one hour - four U.S. Dollar[s] and 25 cents. Likewise, twelve hours for a job in a day, and seven days of the week. I said okay to them because the salary was good for me.</p>\
            <p>After two days one U.S. person came and said that you don't have [a] job in food servicing area, but there is a job in general labor. If you're interested, then you can join. So I said I got selected for food servicing. So I would like to work with that department. Plus, the payment was good - $4.25. But for general labor it was $2.25. So I told them from India, they said something but now in Dubai you are telling something else. Then he said if you are interested then come, [or] else go back to India.</p>",
            vidgrp1vid2: "<p>And he had this brand new sports car and I was like, \"Wow, this is great!\" And I get in and we pull out of the parking lot of the high school and he turned right but I lived left and I said, \"Whoa, wait, I lived that way,\" and he said, \"Oh, I know, but I just have to run home and grab something that I forgot.\" Now warning signs went off in my head because my parents had had a lot of conversations with their only daughter, and I just excused it all away. I thought this possibly can't be anything bad. I know this person, I go to church with him, I go to school with him, it's fine. So I ignored all those feelings and we pull up to his house, which was huge. And he said, \"Hey, would you like to come in? I just have to grab something fast.\" And that day I said everything that my mom had ever taught me. I said, \"No, no, no, I can't, I need to get home. My mom is waiting for me.\" But after all these months, after all these compliments, my life changed with three words. He said, \"I like you.\" That's all it took. I thought, \"Oh, okay.\" And it would be okay. And I went in, and he gave me a tour of the house and he gave me a pop. I thought that was so nice of him. Unfortunately, that pop was laced with drugs. And that afternoon, I got drugged and then raped. Afterwards, he drove me home. And as I went inside to my house, I made another really bad decision. I decided not to tell my mom. And looking back, my whole life would be totally different had I just confided that in her.</p>\
            <p>Several days later, I went back to school on Monday and I saw him again. And he said I need to speak to you. And it wasn't a request. It was a demand. He showed me an envelope. Then the envelope was full of photos. Today, this would be sexting. He said, \"My two older cousins were there while we were there and they took these photos and they have a plan. And the plan is that you're going to earn them back or else.\" I had no idea what he meant. I thought he meant like wash their car, do their homework, work in their store. I had no idea what they had planned for me. And I couldn't imagine that somebody would threaten me and blackmail me to do anything that was outside of what I thought anybody would ever do. And I was like, \"You're, you're crazy. I can't do this. No way.\" And he said, \"Well, you will because we know where your dad works. This is the name of your dad's company. This is the address. This is the name of his boss. We're going to take these photos and show them all around his office.\" I was pretty sure if that happened, my dad would be fired. He said, \"We're going to post these all around school where you're new.\" You know that what would that would have done to my reputation. And then kind of the bottom line for me, the clincher was he said, \"We're going to show these to the priest at church.\" Now, my church was the only support that I had growing up. It never changed no matter where I lived, and I was really involved in my church. I was there every Wednesday for education. I was sing-I sing in the youth choir and I, I loved my church, and I knew there was no way I could let the priest see that because then he would tell my parents, and it would be horrible. So I said okay I'll do what you said. But I didn't even know what that was.</p>\
            <p>They would take me all around the Detroit area to beautiful houses where they would deliver me like a pizza. And I would be taken into these homes down to the basement where all of these men waited for me. There would always be a bedroom, and I would be shut in that bedroom. And I would have to await man after man after man to do whatever they wanted until they were finished.</p>",
            vidgrp1vid3: "<p>My name is Ishmael Alfred Charles, I am a former child soldier. They found us and captured us and brought us into the township of Kaima because we were staying in the forest of the village. When we came into the township, they engaged us. They started off to train us into shooting, but I will always pretend to be someone who is confused and pretending to be like a fool. And because I was always pretending to be a fool, they took those of us who pretended not to understand how to shoot the gun as laborers. So they will use us to carry the looted items that they have. The looted items - that includes clothing, music sets and many, many other things - because the rebels at those times couldn't buy anything that they need, whether to eat, to wear, or to sleep. They will just go right ahead on a consistent basis and break into people's shop and get what they want. So we were the carriers. I unfortunately witnessed a lot of very scary things. The conflict in Sierra Leone was marred by complete madness. Warring rebels will argue about the kind of child a woman will give back to for a pregnant woman, just so that they can split that woman and kill her, and literally kill the baby, also. They will rape women and young girls. They will take young women and girls as what we call bush wives that they do not officially marry, but then forced them to become their wives. And we were exposed to all those realities on a consistent basis every day of our life.</p>"
        }
    },
    {
        title: "",
        url: "L01_010_4.html",
        transcript: {
            vid3: "<p>In Africa, we face multiple issues that our Combating Trafficking in Persons program must address. For example, child soldiering is a problem in countries such as Nigeria, Rwanda, Somalia, Sudan, South Sudan, and the Democratic Republic of the Congo. According to UNICEF, there are more than 17,000 child soldiers in South Sudan alone. These children fight for both rebel forces and the government. They carry AK-47s and M-16s on the front lines of combat while also serving as human mine detectors and suicidal agents; one out of every five suicide bombers in this region is a child. Trafficking of young females in places like Nigeria, Niger, and Cameroon is also a serious problem.</p>\
            <p>Boko Haram, insurgent organizations and militant Islamic groups promise these young women to their soldiers as wives and to work in their camps. Training to familiarize ourselves with these issues is the first step in putting an end to this crime in our area of responsibility.</p>",
            vid4: "<p>In the Middle East, thousands of Other Country Nationals, or OCNs, are hired under U.S. government contracts to work on U.S. Military installations in Iraq and Afghanistan. This large civilian workforce comes primarily from developing countries such as Nepal, India, Bangladesh, Sri Lanka, the Philippines, and Uganda.</p>\
            <p>Although the U.S. Government has a zero-tolerance policy for human trafficking, OCNs can still be vulnerable to deceptive hiring practices, substandard living conditions, unsafe or hazardous working conditions, and other forms of abuse. These workers can become an unstable element on military installations.</p>\
            <p>In addition, militant Islamic terrorist organizations engage in trafficking as a means of making money. Funds from human trafficking are used by organized criminal networks, warlords, and other rogue armed forces to further destabilize weak democracies.</p>\
            <p>If you see any signs of human trafficking, you should report it to your chain of command.</p>",
            vid5: "<p>In South and Central America, trafficking in persons exists in various forms; including sex trafficking, labor trafficking, and child soldiering. Latin America is a primary source region for victims trafficked to the United States, including by transnational criminal networks like MS-13. If you see signs of labor trafficking, report this to contracting personnel and through your chain of command.</p>"
        }
    },
    {
        title: "",
        url: "L01_020a.html",
        transcript: ""
    },
    {
        title: "",
        url: "L01_030.html",
        transcript: {
            vid1: "<p>Knowing about off limits establishments is important, and situational awareness is equally important. In areas of conflict, an understanding of the people, cultures, and environment of the region can help you know how these elements affect the mission.</p>",
            vid2: "<p>Human trafficking can also happen in and around U.S. Military installations. Human trafficking doesn’t stop at prostitution or even sex trafficking. Men, women, and children are also trafficked for forced labor and in some cases on the very subcontracts that support our U.S. Military installation operations.</p>\
            <p>Traffickers look for victims in vulnerable situations due to economic hardship, political instability, natural disasters, and other causes. Traffickers also exploit people who are vulnerable because of their age, social, economic, or immigration status. As defined in the Federal Acquisition Regulation (FAR) Subpart 22.17, severe forms of trafficking involve the recruitment, harboring, transportation, provision, patronizing, soliciting, or obtaining of a person for labor or services, using force, fraud, or coercion for the purpose of forced labor. Human trafficking crimes, occurring on U.S. Military installations, compromise the security of day-to-day operations and require us to practice vigilance—not just when deployed—but even on the Homefront.</p>",
            vid3: "<p>Some common labor trafficking practices include fraudulent recruiting with promises of well-paying jobs, charging recruiting fees, not providing contracts in the employee’s native language, confiscating passports, not paying employees in a timely manner, and providing unsafe or unsanitary living or working conditions.</p>\
            <p>Employees who have fallen victim to such illicit practices may be scared to report issues due to fear of reprisal. If you see signs of distress or indicators that an employee’s communication is being limited by the employer, you should report through your chain of command.</p>",
            vid4: "<p>United States military and civilian forces strive to promote our interests abroad and to protect our freedoms at home. We interact and ally on a daily basis with local civilians, government, and military personnel around the world.</p>\
            <p>In performance of our duties, U.S. forces may encounter terrible crimes and serious human rights violations such as sex trafficking, forced labor, slavery, kidnapping, torture, and child soldiers. These acts, when performed under color of law, meaning committed under official capacity, rise to the level of “Gross Violations of Human Rights.”</p>\
            <p>United States law and DoD policy define a number of inhumane acts as Gross Violations of Human Rights, including but not limited to many forms of Trafficking in Persons.</p>\
            <p>Historically, U.S. forces encountered these violations: In WWII, Korean women were forced into prostitution to serve as “comfort women” to Japanese soldiers; in southeast Asia, Burmese minorities were trafficked for labor and prostitution by Burmese military forces; and more recently, in some Middle East and African countries, children are conscripted to serve as soldiers, porters, cooks, miners, and sex slaves.</p>\
            <p>So, what should we do when we see or suspect a Gross Violation of Human Rights?</p>\
            <p>Consider the DoD’s response to a situation of great concern in Afghanistan. In spite of a state-supported ban, several members of the Afghan Security Forces continued to take part in the tradition of bacha bazi, in English: “dancing boys.” In private parties, young boys dressed as girls, forced to dance for the entertainment of the men, passed around and often used for sex. The practice is a form of human trafficking, and when the participants are uniformed forces and the crime is committed under color of law, it is also a Gross Violation of Human Rights.</p>\
            <p>In Afghanistan, the program manager for the DoD’s Combatting Trafficking in Persons, or CTIP, Program Management Office briefs all new arrivals at Bagram Air Base so they’ll know what to look for, and how to immediately report suspected violations, such as bacha bazi.</p>\
            <p>CHARMANE JOHNSON, CTIP PROGRAM MANAGER, U.S. FORCES – AFGHANISTAN: “It’s important to know that our OCONUS CTIP mission here operates from a foundation of shared understanding that human dignity and respect are force multipliers, so we will continue to do the hard work to move the needle forward to ensure these heinous crimes and incidents do not happen within our military footprint.”</p>\
            <p>U.S. Forces under the U.S. Southern Command also encounter Gross Violations of Human Rights.</p>\
            <p>SOUTHCOM’s Human Rights office delivers required training to all deploying personnel and issues a standing orders “pocket card” to remind them of the 5 Rs of their mandated reporting in accordance with SOUTHCOM’s zero tolerance policy for human rights violations.</p>\
            <p>If you witness or suspect a violation, take action. The DoD’s position is clear: Any suspected trafficking in persons or other human rights violations must be reported immediately. Each regional command has a mandated reporting chain based on the region. So now is the time to make sure you know the reporting channels of your particular AOR, and to be prepared at all times to See It, Report it!</p>"
        }
    },
    {
        title: "",
        url: "L01_040.html",
        transcript: {
            vid1: "<p>Everyone has a role to play in combating human trafficking. Reporting suspected TIP violations makes a difference and, in some cases, has saved lives. Your everyday decisions impact the culture and climate for mission readiness in the DoD. Not only do you have a responsibility to record and report any human rights violations you may witness, but it is also your responsibility to avoid establishments that show indicators of trafficking in persons, and report these establishments to your chain of command. When you ignore a situation that appears to involve trafficking in persons, you compromise not only the safety of the victims involved, but also the safety of those in your unit and the region as a whole. Nothing can be done to solve a problem that no one knows about.</p>\
            <p>On the other hand, you might be inclined to investigate a situation or to rescue a person. It is not safe to act on your own and not your responsibility to investigate a situation. If you suspect trafficking in persons, you should first report the incident through your chain of command and local or command-level Inspector General’s office. You can also call the Department of Defense IG Hotline.</p>"
        }
    },
    {
        title: "",
        url: "L01_050a.html",
        transcript: ""
    }
];